### ISSUE TITLE
Where's the executable jar of this tool?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [borisf/classyshark-calculate-size#2]
Also, does it support opening APK files ? I think it should be easy to add this, as the needed files are within...

**Comment by borisf** [comment]
Not sure I get:
1. Executables (jars) are right here, look under [releases](https://github.com/borisf/classyshark-calculate-size/releases)

2. No this tool doesn't opening APK files. For opening APKs use ClassyShark

**Comment by AndroidDeveloperLB** [comment]
1. The first step on the main screen of this repo, that looks like :

> Download ClassyShark Size Calculator

Goes to this website:
https://github.com/borisf/classyshark-calculate-size

So I asked where is this jar, because it actually stays on the same website...

2. What is the difference between them? One for Android, and one for Java? Why not have one tool that can handle both? Isn't it just a matter of getting the classes file from within the APK ?

**Comment by borisf** [comment]
Thanks

1. Fixed the release link now

2. ClassyShark Calc Size (this project) creates a classes.dex file from your dependency. ClassyShark main is the viewer for classes.dex entries. They solve different problems along the pipeline (generate versus view).

Please let me know if this description doesn't make sense. And I am happy to receive pull requests
